sonar.projectKey=modul3-activity-manager
sonar.projectName=Modul 3 - Activity Manager

sonar.sources=app,routes,resources

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/build/**

sonar.sourceEncoding=UTF-8
